services:
  - type: web
    name: ioagent
    env: python
    region: oregon
    plan: free
    buildCommand: |
      pip install --upgrade pip
      pip install -r requirements.txt
      python init_production_db.py || echo "Database initialization failed, will retry on startup"
    startCommand: python app.py
    envVars:
      - key: FLASK_ENV
        value: production
      - key: SECRET_KEY
        generateValue: true
      - key: JWT_SECRET_KEY
        generateValue: true
      # - key: DATABASE_URL
      #   value: postgresql://ioagent_user:uOXBZaleReg83smdsLXM371fT6vpVF4C@dpg-d1cbuv6uk2gs73aii0d0-a/ioagent
      # PostgreSQL temporarily disabled - using SQLite
      - key: PROD_CORS_ORIGINS
        value: https://ioagent.onrender.com
      - key: PYTHON_VERSION
        value: 3.11.0