services:
  - type: web
    name: ioagent
    env: python
    region: oregon
    plan: free
    buildCommand: pip install -r IOAgent-backend/requirements.txt
    startCommand: cd IOAgent-backend && python app.py
    envVars:
      - key: FLASK_ENV
        value: production
      - key: SECRET_KEY
        generateValue: true
      - key: JWT_SECRET_KEY
        generateValue: true
      - key: PROD_CORS_ORIGINS
        value: https://ioagent.onrender.com
      - key: PYTHON_VERSION
        value: 3.11.0